version: "3"
services:
  # Add app-dev?
  app:
    build: .
    image: fizwidget/budget-tracker
    ports:
      - "8080:8080" # For GraphQL API
      - "5005:5005" # For debugger
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    restart: unless-stopped
    depends_on:
      - database
  database:
    image: postgres:12.1
    ports:
      - "5432:5432" # For connecting via database explorer tool
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    restart: unless-stopped